let allMusic = [
  {
    name: "Tum Hi Ho",
    artist: "Arijit Singh",
    img: "music-1",
    src: "music-1",
  },
  {
    name: "Muskurane ",
    artist: "Arijit Singh",
    img: "music-2",
    src: "music-2",
  },
  {
    name: "Janam Janam Dilwale",
    artist: "Arijit Singh",
    img: "music-3",
    src: "music-3",
  },
  {
    name: "Main Rang Sharbaton Ka",
    artist: "Arijit Singh",
    img: "music-4",
    src: "music-4",
  },
  {
    name: "Agar Tum Saath Ho",
    artist: "Arijit Singh",
    img: "music-5",
    src: "music-5",
  },
  {
    name: "Dhadak",
    artist: "Arijit Singh",
    img: "music-6",
    src: "music-6",
  },
  {
    name: "Kabhi Jo Badal Barse",
    artist: "Arijit Singh",
    img: "music-7",
    src: "music-7",
  },
  {
    name: "Enna Sona",
    artist: "Arijit Singh",
    img: "music-8",
    src: "music-8",
  },
  {
    name: "Gerua",
    artist: "Arijit Singh",
    img: "music-9",
    src: "music-9",
  },
  {
    name: "Tera Fitoor",
    artist: "Arijit Singh",
    img: "music-10",
    src: "music-10",
  },
  {
    name: "Tera Hone Laga Hoon",
    artist: "Atif Aslam",
    img: "music-11",
    src: "music-11",
  },
  {
    name: " Ae Dil Hai Mushkil",
    artist: "Arijit Singh",
    img: "music-12",
    src: "music-12",
  },
  {
    name: "Hawayein",
    artist: "Arijit Singh",
    img: "music-13",
    src: "music-13",
  },
  {
    name: "Zaalima (Raees)",
    artist: "Arijit Singh",
    img: "music-14",
    src: "music-14",
  },
  {
    name: "Tu Jaane Na",
    artist: "Atif Aslam",
    img: "music-15",
    src: "music-15",
  },
];
